House.create([
                 {
                     name: "Gryffindor",
                     head: "Minerva McGonagall",
                     ghost: "Nearly Headless Nick",
                     founder: "Goderic Gryffindor",
                     values: %w(courage bravery nerve chivalry),
                     colors: %w(scarlet gold)
                 },
                 {
                     name: "Ravenclaw",
                     head: "Fillius Flitwick",
                     ghost: "The Grey Lady",
                     founder: "Rowena Ravenclaw",
                     values: %w(intelligence creativity learning wit),
                     colors: %w(blue bronze)
                 },
                 {
                     name: "Slytherin",
                     head: "Severus Snape",
                     ghost: "The Bloody Baron",
                     founder: "Salazar Slytherin",
                     values: %w(ambition cunning leadership resourcefulness),
                     colors: %w(green silver)
                 },
                 {
                     name: "Hufflepuff",
                     head: "Pomona Sprout",
                     ghost: "The Fat Friar",
                     founder: "Helga Hufflepuff",
                     values: %w(patience justice loyalty),
                     colors: %w(yellow black)
                 }
             ])

gryffindor = House.find_by(name: "Gryffindor")
ravenclaw = House.find_by(name: "Ravenclaw")
slytherin = House.find_by(name: "Slytherin")
hufflepuff = House.find_by(name: "Hufflepuff")

Character.create([
                     {
                         name: "Hannah Abbott",
                         role: "student",
                         house: hufflepuff,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Bathsheda Babbling",
                         role: "Professor, Ancient Runes",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Ludo Bagman",
                         role: "Head, Department of Magical Games and Sports",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Bathilda Bagshot",
                         role: "Author, A History Of Magic",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Katie Bell",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Cuthbert Binns",
                         role: "Professor, History of Magic",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Phineas Nigellus Black",
                         role: "(Formerly) Headmaster of Hogwarts",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Regulus Black",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Sirius Black",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Amelia Bones",
                         role: "Head, Department of Magical Law Enforcement",
                         house: hufflepuff,
                         ministry_of_magic: true,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Susan Bones",
                         role: "student",
                         house: hufflepuff,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Terry Boot",
                         role: "student",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Lavender Brown",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Millicent Bulstrode",
                         role: "student",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Frank Bryce",
                         role: "Gardener, Riddle Family",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Charity Burbage",
                         role: "Professor, Muggle Studies",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Alecto Carrow",
                         role: "Professor, Muggle Studies",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Amycus Carrow",
                         role: "Professor, Dark Arts",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Reginald Cattermole",
                         role: "Employee, Magical Maintenance Department",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Mary Cattermole",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Cho Chang",
                         role: "Student",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Penelope Clearwater",
                         role: "Student",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Michael Corner",
                         role: "Student",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Crabbe",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Vincent Crabbe",
                         role: "Student",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Colin Creevey",
                         role: "Student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Dennis Creevey",
                         role: "Student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Dirk Cresswell",
                         role: "Head, Goblin Liason Office",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Bartemius Crouch Sr.",
                         role: "Head, Department of International Magical Cooperation",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Bartemius Crouch Jr.",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "John Dawlish",
                         role: "Auror",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Fleur Delacour",
                         role: "Student",
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Gabrielle Delacour",
                         role: "Student",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Dedalus Diggle",
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Amos Diggory",
                         role: "Employee, Department for the Regulation and Control of Magical Creatures",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Cedric Diggory",
                         role: "Student",
                         house: hufflepuff,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Elphias Doge",
                         role: "Special Advisor to the Wizengamot",
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Antonin Dolohov",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Aberforth Dumbledore",
                         role: "Owner, Hog's Head Inn",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Albus Dumbledore",
                         role: "Headmaster, Hogwarts",
                         house: gryffindor,
                         ministry_of_magic: true,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Ariana Dumbledore",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Dudley Dursley",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Marjorie Dursley",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Petunia Dursley",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Vernon Dursley",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Marietta Edgecombe",
                         role: "student",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Everard",
                         role: "(former) Headmaster, Hogwarts",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Arabella Figg",
                         role: "Dealer of cross-bread cats and kneazies",
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Argus Filch",
                         role: "Caretaker, Hogwarts",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Justin Finch-Fletchley",
                         role: "student",
                         house: hufflepuff,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Seamus Finnigan",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Marcus Flint",
                         role: "student",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Nicolas Flamel",
                         role: "Alchemist",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Mundungus Fletcher",
                         role: "Dealer of Wizarding Artifacts",
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Filius Flitwick",
                         role: "Professor, Charms",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Cornelius Fudge",
                         role: "Minister of Magic",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Marvolo Gaunt",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Merope Gaunt",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Morfin Gaunt",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Anthony Goldstein",
                         role: "student",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Goyle Sr.",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Gregory Goyle",
                         role: "student",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Hermione Granger",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Mykew Gregorovitch",
                         role: "Wand Maker",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Fenrir Greyback",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Gellert Grindelwald",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Wilhelmina Grubbly-Plank",
                         role: "Professor, Care of Magical Creatures",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Godric Gryffindor",
                         role: "Founder, Hogwarts",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Rubeus Hagrid",
                         role: "Groundkeeper, Professor, Care of Magical Creatures",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Rolanda Hooch",
                         role: "Quidditch Referee ",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Mafalda Hopkirk",
                         role: "Assistant, mproper Use of Magic Office",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Helgahufflepuff",
                         role: "Founder, Hogwarts",
                         house: hufflepuff,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Angelina Johnson",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Lee Jordan",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Bertha Jorkins",
                         role: "Department of Magical Games and Sports Employee",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Igor Karkaroff",
                         role: "Headmaster, Durmstrang",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Viktor Krum",
                         role: "Bulgarian Quiddich Seeker",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Bellatrix Lestrange",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Rabastan Lestrange",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Rodolphus Lestrange",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Gilderoy Lockhart",
                         role: "Professor, Defense Against the Dark Arts",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Alice Longbottom",
                         role: "Auror (formerly)",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Frank Longbottom",
                         role: "Auror (formerly)",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Augusta Longbottom",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Neville Longbottom",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Luna Lovegood",
                         role: "student",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Xenophilius Lovegood",
                         role: "Editor, The Quibbler",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Remus Lupin",
                         role: "Professor, Defence Against the Dark Arts",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Walden Macnair",
                         role: "Executioner, Committee of Disposal of Dangerous Creatures",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Draco Malfoy",
                         role: "student",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Lucius Malfoy",
                         role: "School Governer of Hogwarts",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Narcissa Malfoy",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Madam Malkin",
                         role: "Shop Owner, Madam Malkin's Robes for All Occasions",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Olympe Maxime",
                         role: "Headmistress, Beauxbatons Academy of Magic",
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Ernest Macmillan",
                         role: "student",
                         house: hufflepuff,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Minerva McGonagall",
                         role: "Professor, Transfiguration",
                         house: gryffindor,
                         ministry_of_magic: true,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Alastor Moody",
                         ministry_of_magic: true,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Theodore Nott",
                         role: "student",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Garrick Ollivander",
                         role: "Wandmaker",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Pansy Parkinson",
                         role: "student",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Padma Patil",
                         role: "student",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Parvati Patil",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Peter Pettigrew",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Antioch Peverell",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Cadmus Peverell",
                         role: "Owner of the resurrection stone",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Ignotus Peverell",
                         role: "Owner of the invisibility cloak",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Irma Pince",
                         role: "Librarian, Hogwarts",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Sturgis Podmore",
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Poppy Pomfrey",
                         role: "Matron, Hogwarts Hospital Wing",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Harry Potter",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "James Potter I",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Lily J. Potter",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Ernest Prang",
                         role: "Driver of the Knight Bus",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Quirinus Quirrell",
                         role: "Professor, Defence Against the Dark Arts",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Helena Ravenclaw",
                         role: "Ravenclaw House Ghost",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Rowena Ravenclaw",
                         role: "Founder, Hogwarts",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Mary Riddle",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Thomas Riddle",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Tom Riddle Sr",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Tom Riddle",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Demelza Robins",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Augustus Rockwood",
                         role: "Unspeakable",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Albert Runcorn",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Scabior",
                         role: "Snatcher",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Newton Scamander ",
                         role: "Author, Fantastic Beasts and Where to Find Them",
                         house: hufflepuff,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Rufus Scrimgeour",
                         role: "Head of Auror Office",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Kingsley Shacklebolt",
                         role: "Auror",
                         ministry_of_magic: true,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Stanley Shunpike",
                         role: "Conductor of the Knight Bus",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Aurora Sinistra",
                         role: "Professor, Astronomy",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Rita Skeeter",
                         role: "Gossip Correspondant for the Daily Prophet",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Horace Slughorn",
                         role: "Professor, Potions",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Salazar Slytherin",
                         role: "Founder, Hogwarts",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Hepzibah Smith",
                         house: hufflepuff,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Zacharias Smith",
                         role: "student",
                         house: hufflepuff,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Severus Snape",
                         role: "Professor, Potions",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: true,
                     },
                     {
                         name: "Alicia Spinnet",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Pomona Sprout",
                         role: "Professor, Herbology",
                         house: hufflepuff,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Pius Thicknesse",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Dean Thomas",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Andromeda Tonks",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Nymphadora Tonks",
                         role: "Auror",
                         house: hufflepuff,
                         ministry_of_magic: true,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Edward Tonks",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Travers",
                         role: "Ministry of Magic Official",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Sybill Trelawney",
                         role: "Professor, Divination",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Dolores Umbridge",
                         role: "Head of the Muggle Born Registration Commission",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Emmeline Vance",
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Romilda Vane",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Septima Vector",
                         role: "Professor, Arithmancy",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Arthur Weasley",
                         role: "Head, Misuse of Muggle Artifacts ",
                         house: gryffindor,
                         ministry_of_magic: true,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "William Weasley",
                         role: "Curse Breaker, Gringotts Bank",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Charles Weasley",
                         role: "Dragonologist",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Fred Weasley",
                         role: "co-owner of Weasleys' Wizard Wheezes",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "George Weasley",
                         role: "co-owner of Weasleys' Wizard Wheezes",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Ginevra Weasley",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Molly Weasley",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Percy Weasley",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Ronald Weasley",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: true,
                         death_eater: false,
                     },
                     {
                         name: "Oliver Wood",
                         role: "student",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Kennilworthy Whisp",
                         role: "Author, Quiddich Through The Ages",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Corban Yaxley",
                         ministry_of_magic: true,
                         order_of_phoenix: false,
                         death_eater: true,
                     },
                     {
                         name: "Blaise Zabini",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Aragog",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Bane",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Beedle the Bard",
                         role: "Fairytale Author",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Bloody Baron",
                         role: "Slytherin House Ghost",
                         house: slytherin,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Buckbeak",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Cadogan",
                         role: "Gryffindor Tower Door Guard",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Crookshanks",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Dobby",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Errol",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Fang",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Fat Friar",
                         role: "Hufflepuff House Ghost",
                         house: hufflepuff,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Fridfwulfa",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Fat Lady",
                         role: "Gryffindor Tower Door Guard",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Fawkes",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Firenze",
                         role: "Professor, Divination",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Fluffy",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Grawp",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Griphook",
                         role: "Employee, Gringotts Wizarding Bank",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Hedwig",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Hokey",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Kreacher",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Magorian",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Myrtle Warren",
                         role: "student",
                         house: ravenclaw,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Mrs. Norris",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Great Aunt Muriel",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Nagini",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Nicholas de Mimsy-Porpington",
                         role: "Gryffindor House Ghost",
                         house: gryffindor,
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Peeves",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Pigwidgeon",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                     {
                         name: "Madam Rosmerta",
                         role: "Owner, The Three Broomsticks",
                         ministry_of_magic: false,
                         order_of_phoenix: false,
                         death_eater: false,
                     },
                 ])

Spell.create([
                 {
                     name: "Aberto",
                     kind: :charm,
                     effect: "opens objects"
                 },
                 {
                     name: "Accio",
                     kind: :charm,
                     effect: "Summons an object",
                 },
                 {
                     name: "Aguamenti",
                     kind: :charm,
                     effect: "shoots water from wand",
                 },
                 {
                     name: "Alarte Ascendare",
                     kind: :spell,
                     effect: "shoots things high in the air",
                 },
                 {
                     name: "Alohomora",
                     kind: :charm,
                     effect: "opens locked objects",
                 },
                 {
                     name: "Anapneo",
                     kind: :spell,
                     effect: "clears the target's airway",
                 },
                 {
                     name: "Anti-Cheating",
                     kind: :spell,
                     effect: "prevents cheating on exams",
                 },
                 {
                     name: "Aparecium",
                     kind: :spell,
                     effect: "reveals invisible ink",
                 },
                 {
                     name: "Apparate",
                     kind: :spell,
                     effect: "teleportation spell",
                 },
                 {
                     name: "Arania Exumai",
                     kind: :spell,
                     effect: "blasts away spiders",
                 },
                 {
                     name: "Aqua Eructo",
                     kind: :spell,
                     effect: "shoots water from wand",
                 },
                 {
                     name: "Arresto Momentum",
                     kind: :spell,
                     effect: "slows down objects",
                 },
                 {
                     name: "Ascendio",
                     kind: :spell,
                     effect: "moves an object upward",
                 },
                 {
                     name: "Avada Kedavra",
                     kind: :curse,
                     effect: "murders opponent",
                 },
                 {
                     name: "Avifors",
                     kind: :charm,
                     effect: "turns small objects into birds",
                 },
                 {
                     name: "Avis",
                     kind: :spell,
                     effect: "launches birds from your wand",
                 },
                 {
                     name: "Babbling Curse",
                     kind: :curse,
                     effect: "makes a person babble",
                 },
                 {
                     name: "Bombarda",
                     kind: :spell,
                     effect: "causes explosions",
                 },
                 {
                     name: "Bombarda Maxima",
                     kind: :spell,
                     effect: "causes large explosions",
                 },
                 {
                     name: "Bubble Head",
                     kind: :charm,
                     effect: "puts a person's head in a protective air bubble",
                 },
                 {
                     name: "Carpe Retractum",
                     kind: :spell,
                     effect: "shoots a rope from a wand to snag things",
                 },
                 {
                     name: "Caterwauling",
                     kind: :charm,
                     effect: "detects enemies and emits a scream",
                 },
                 {
                     name: "Cave Inimicum",
                     kind: :charm,
                     effect: "detects enemies and emits an alarm",
                 },
                 {
                     name: "Cheering",
                     kind: :charm,
                     effect: "makes a person happy and giddy",
                 },
                 {
                     name: "Cistem Aperio",
                     kind: :spell,
                     effect: "opens things",
                 },
                 {
                     name: "Colloportus",
                     kind: :spell,
                     effect: "locks doors",
                 },
                 {
                     name: "Colloshoo",
                     kind: :spell,
                     effect: "makes a person's shoes stick to the ground",
                 },
                 {
                     name: "Colovaria",
                     kind: :charm,
                     effect: "makes an object change colour",
                 },
                 {
                     name: "Confringo",
                     kind: :curse,
                     effect: "explode flames on target",
                 },
                 {
                     name: "Confundus",
                     kind: :charm,
                     effect: "used to confuse opponent",
                 },
                 {
                     name: "Conjunctivitis",
                     kind: :curse,
                     effect: "damages opponent's eyesight",
                 },
                 {
                     name: "Cornflake Skin",
                     kind: :curse,
                     effect: "gives a person cereal skin",
                 },
                 {
                     name: "Crucio",
                     kind: :curse,
                     effect: "tortures a person",
                 },
                 {
                     name: "Cushioning",
                     kind: :charm,
                     effect: "helps cushon a fall",
                 },
                 {
                     name: "Defodio",
                     kind: :spell,
                     effect: "dig out materials",
                 },
                 {
                     name: "Deletrius",
                     kind: :spell,
                     effect: "counters \"Prior Incantato\"",
                 },
                 {
                     name: "Densaugeo",
                     kind: :spell,
                     effect: "enlarges teeth",
                 },
                 {
                     name: "Deprimo",
                     kind: :spell,
                     effect: "wind damaging spell",
                 },
                 {
                     name: "Depulso",
                     kind: :charm,
                     effect: "drives an object away",
                 },
                 {
                     name: "Descendo",
                     kind: :spell,
                     effect: "moves an object downwards",
                 },
                 {
                     name: "Diffindo",
                     kind: :spell,
                     effect: "splits seams",
                 },
                 {
                     name: "Diminuendo",
                     kind: :spell,
                     effect: "shrinks the target",
                 },
                 {
                     name: "Dissendium",
                     kind: :spell,
                     effect: "opens passageways",
                 },
                 {
                     name: "Disillusionment",
                     kind: :charm,
                     effect: "makes the target blend into the surroundings",
                 },
                 {
                     name: "Duro",
                     kind: :spell,
                     effect: "makes objects hard",
                 },
                 {
                     name: "Drought",
                     kind: :charm,
                     effect: "dries up puddles",
                 },
                 {
                     name: "Ears to Kumquats",
                     kind: :spell,
                     effect: "gives a person kumquat ears",
                 },
                 {
                     name: "Ear Shriveling ",
                     kind: :curse,
                     effect: "cause a person's ear to shrivel",
                 },
                 {
                     name: "Engorgio",
                     kind: :charm,
                     effect: "enlarges an item",
                 },
                 {
                     name: "Ennervate",
                     kind: :spell,
                     effect: "counters Stupefy",
                 },
                 {
                     name: "Entrail-Expelling",
                     kind: :curse,
                     effect: "expel entrails from a body",
                 },
                 {
                     name: "Episkey",
                     kind: :spell,
                     effect: "heals minor injuries",
                 },
                 {
                     name: "Epoximise",
                     kind: :spell,
                     effect: "binds objects together",
                 },
                 {
                     name: "Erecto",
                     kind: :spell,
                     effect: "builds things",
                 },
                 {
                     name: "Evanesco",
                     kind: :spell,
                     effect: "makes things vanish",
                 },
                 {
                     name: "Everte Statum",
                     kind: :spell,
                     effect: "throws a victim backwards",
                 },
                 {
                     name: "Expecto Patronum",
                     kind: :charm,
                     effect: "creates a Patronus",
                 },
                 {
                     name: "Expelliarmus",
                     kind: :charm,
                     effect: "disarms your opponent",
                 },
                 {
                     name: "Expulso",
                     kind: :spell,
                     effect: "makes objects explode",
                 },
                 {
                     name: "Extinguishing",
                     kind: :spell,
                     effect: "puts out fires",
                 },
                 {
                     name: "Ferula",
                     kind: :spell,
                     effect: "creates bandages",
                 },
                 {
                     name: "Fianto Duri",
                     kind: :charm,
                     effect: "defensive charm",
                 },
                 {
                     name: "Fidelius",
                     kind: :charm,
                     effect: "hides a secret within someone",
                 },
                 {
                     name: "Fiendfyre",
                     kind: :curse,
                     effect: "hard to control large fire curse",
                 },
                 {
                     name: "Finestra",
                     kind: :spell,
                     effect: "turns windows to dust",
                 },
                 {
                     name: "Finite",
                     kind: :spell,
                     effect: "finishes spell in the caster's area",
                 },
                 {
                     name: "Finite Incantatum",
                     kind: :spell,
                     effect: "stops any current spells",
                 },
                 {
                     name: "Flagrante",
                     kind: :curse,
                     effect: "multiplies and burns objects upon touch",
                 },
                 {
                     name: "Flagrate",
                     kind: :spell,
                     effect: "allows user to write on objects",
                 },
                 {
                     name: "Flame Freezing",
                     kind: :charm,
                     effect: "makes flames cool",
                 },
                 {
                     name: "Flying",
                     kind: :charm,
                     effect: "makes objects fly",
                 },
                 {
                     name: "Fumos",
                     kind: :spell,
                     effect: "a defensive cloud of smoke",
                 },
                 {
                     name: "Furnunculus",
                     kind: :curse,
                     effect: "produces boils on opponent",
                 },
                 {
                     name: "Geminio",
                     kind: :spell,
                     effect: "duplicates an object",
                 },
                 {
                     name: "Glisseo",
                     kind: :spell,
                     effect: "turns stairs into ramps",
                 },
                 {
                     name: "Gripping",
                     kind: :charm,
                     effect: "makes it easier to hold things",
                 },
                 {
                     name: "Harmonia Nectere Passus",
                     kind: :spell,
                     effect: "mends broken things",
                 },
                 {
                     name: "Homenum Revelio",
                     kind: :spell,
                     effect: "reveals humans nearby",
                 },
                 {
                     name: "Homonculous",
                     kind: :charm,
                     effect: "lets a person track another's movement on a map",
                 },
                 {
                     name: "Homorphus",
                     kind: :charm,
                     effect: "Lockhart's warewolf \"cure\"",
                 },
                 {
                     name: "Horcrux",
                     kind: :curse,
                     effect: "allows wizard to put their soul into an object",
                 },
                 {
                     name: "Illegibilus",
                     kind: :spell,
                     effect: "makes text unreadable",
                 },
                 {
                     name: "Immobulus",
                     kind: :charm,
                     effect: "renders target immobile",
                 },
                 {
                     name: "Impedimenta",
                     kind: :charm,
                     effect: "slows an advancing object",
                 },
                 {
                     name: "Imperio",
                     kind: :curse,
                     effect: "controls a person",
                 },
                 {
                     name: "Impervius",
                     kind: :charm,
                     effect: "makes an object repel water",
                 },
                 {
                     name: "Incarcerous",
                     kind: :spell,
                     effect: "ties someone up",
                 },
                 {
                     name: "Incendio",
                     kind: :spell,
                     effect: "starts a fire",
                 },
                 {
                     name: "Lacarnum Inflamarae",
                     kind: :spell,
                     effect: "shoots a fireball from caster's wand",
                 },
                 {
                     name: "Langlock",
                     kind: :spell,
                     effect: "glues opponent's tongue to roof of mouth",
                 },
                 {
                     name: "Legilimens",
                     kind: :spell,
                     effect: "allows caster to read the mind of the target",
                 },
                 {
                     name: "Levicorpus",
                     kind: :spell,
                     effect: "hangs target upside down by feet",
                 },
                 {
                     name: "Liberacorpus",
                     kind: :spell,
                     effect: "counter spell to Levicorpus",
                 },
                 {
                     name: "Locomotor Mortis",
                     kind: :curse,
                     effect: "locks opponent's legs",
                 },
                 {
                     name: "Lumos",
                     kind: :spell,
                     effect: "creates light at wand tip",
                 },
                 {
                     name: "Lumos Maxima",
                     kind: :spell,
                     effect: "creates ball of light that can brighten a room for a long period of time",
                 },
                 {
                     name: "Lumos Solem",
                     kind: :spell,
                     effect: "creates a strong beam of light from the wand",
                 },
                 {
                     name: "Meteolojinx Recanto",
                     kind: :spell,
                     effect: "causes weather effect spells to stop",
                 },
                 {
                     name: "Mimblewimble",
                     kind: :curse,
                     effect: "tongue ties it's target",
                 },
                 {
                     name: "Mobiliarbus",
                     kind: :charm,
                     effect: "moves objects with wand",
                 },
                 {
                     name: "Mobilicorpus",
                     kind: :spell,
                     effect: "moves unconcious bodies",
                 },
                 {
                     name: "Morsmorde",
                     kind: :spell,
                     effect: "conjures the dark mark",
                 },
                 {
                     name: "Morsmorde",
                     kind: :spell,
                     effect: "prevents nearby people from listening to conversations",
                 },
                 {
                     name: "Nox",
                     kind: :spell,
                     effect: "counter to Lumos, turns off light",
                 },
                 {
                     name: "Oculus Reparo",
                     kind: :spell,
                     effect: "repairs eyeglasses",
                 },
                 {
                     name: "Obliteration",
                     kind: :charm,
                     effect: "removes footprints",
                 },
                 {
                     name: "Obliviate",
                     kind: :charm,
                     effect: "erases memories",
                 },
                 {
                     name: "Obscuro",
                     kind: :spell,
                     effect: "blindfolds the victim",
                 },
                 {
                     name: "Oppugno",
                     kind: :spell,
                     effect: "makes conjured items attack",
                 },
                 {
                     name: "Orchideous",
                     kind: :spell,
                     effect: "conjures flowers",
                 },
                 {
                     name: "Periculum",
                     kind: :spell,
                     effect: "makes fireworks from the wand tip",
                 },
                 {
                     name: "Permanent Sticking",
                     kind: :charm,
                     effect: "causes items to permanently stick to things",
                 },
                 {
                     name: "Petrificus Totalus",
                     kind: :spell,
                     effect: "body bind",
                 },
                 {
                     name: "Piertotum Locomotor",
                     kind: :spell,
                     effect: "animates statues and suits of armor",
                 },
                 {
                     name: "Point Me",
                     kind: :charm,
                     effect: "wand acts like a compass",
                 },
                 {
                     name: "Portus",
                     kind: :charm,
                     effect: "makes an object a Portkey",
                 },
                 {
                     name: "Priori Incantatem",
                     kind: :spell,
                     effect: "when sibling wands duel, the weaker wand shows all recently cast spells",
                 },
                 {
                     name: "Prior Incantato",
                     kind: :spell,
                     effect: "reveals a wand's last spell",
                 },
                 {
                     name: "Protego",
                     kind: :charm,
                     effect: "cause spells to reflect back to the sender",
                 },
                 {
                     name: "Protego Totalum",
                     kind: :charm,
                     effect: "area protection charm",
                 },
                 {
                     name: "Quietus",
                     kind: :spell,
                     effect: "counter spell for Sonorous",
                 },
                 {
                     name: "Reducio",
                     kind: :spell,
                     effect: "returns items to original size. counters Engorgio",
                 },
                 {
                     name: "Reducto",
                     kind: :spell,
                     effect: "blasts solid objects aside",
                 },
                 {
                     name: "Relashio",
                     kind: :spell,
                     effect: "releases user from binding",
                 },
                 {
                     name: "Rennervate",
                     kind: :spell,
                     effect: "cures unconciousness",
                 },
                 {
                     name: "Reparo",
                     kind: :spell,
                     effect: "repairs things",
                 },
                 {
                     name: "Repello Muggletum",
                     kind: :spell,
                     effect: "keeps muggles away",
                 },
                 {
                     name: "Repello Inimicum",
                     kind: :spell,
                     effect: "keeps evil beings away",
                 },
                 {
                     name: "Revelio",
                     kind: :spell,
                     effect: "reveals hidden objects",
                 },
                 {
                     name: "Rictusempra",
                     kind: :charm,
                     effect: "tickles target",
                 },
                 {
                     name: "Riddikulus",
                     kind: :spell,
                     effect: "causes target to laugh and defeats Boggarts",
                 },
                 {
                     name: "Salvio Hexia",
                     kind: :spell,
                     effect: "protection against hexes",
                 },
                 {
                     name: "Scourgify",
                     kind: :charm,
                     effect: "cleaning charm",
                 },
                 {
                     name: "Sectumsempra",
                     kind: :spell,
                     effect: "causes wounds as if slashed by a sword",
                 },
                 {
                     name: "Serpensortia",
                     kind: :spell,
                     effect: "produces a snake",
                 },
                 {
                     name: "Silencio",
                     kind: :spell,
                     effect: "silences target",
                 },
                 {
                     name: "Slugulus Eructo",
                     kind: :charm,
                     effect: "makes target vomit slugs",
                 },
                 {
                     name: "Sonorus",
                     kind: :spell,
                     effect: "amplifies voice",
                 },
                 {
                     name: "Specialis Revelio",
                     kind: :spell,
                     effect: "reveals hidden secrets or magical properties",
                 },
                 {
                     name: "Stupefy",
                     kind: :spell,
                     effect: "knocks out target",
                 },
                 {
                     name: "Switching Spell",
                     kind: :spell,
                     effect: "switches objects",
                 },
                 {
                     name: "Tarantallegra",
                     kind: :spell,
                     effect: "forces target to dance",
                 },
                 {
                     name: "Tergeo",
                     kind: :spell,
                     effect: "cleans up messes",
                 },
                 {
                     name: "Unbreakable Vow",
                     kind: :spell,
                     effect: "a vow that if broken, kills you",
                 },
                 {
                     name: "Vulnera Sanentur",
                     kind: :spell,
                     effect: "heals target",
                 },
                 {
                     name: "Waddiwasi",
                     kind: :spell,
                     effect: "unsticks an object",
                 },
                 {
                     name: "Wingardium Leviosa",
                     kind: :charm,
                     effect: "makes an object fly",
                 }
             ])